### ISSUE TITLE
scheduling of workflow stopped working

### ISSUE THREAD

**Issue by dtoledo67** [NirmataOSS/workflow#21]
I have 3 intances of the same application that can generate periodically the workflow. The same 2 apps can executed these workflows. The 3 instances run on 3 EC2 instances. I observed 3 times in the last 10 days that the scheduling of the workflow stopped working. When it happens I see the following exception being generate continuously on all 3 instances:

15:35:57.050 [LeaderSelector-1] DEBUG c.nirmata.workflow.details.Scheduler - initLatch completed
15:35:57.050 [LeaderSelector-1] INFO  c.nirmata.workflow.details.Scheduler - Updating run: Id{id='a14f3b93-bc5e-4b63-9b90-410d331229b6'}
15:35:57.050 [LeaderSelector-1] ERROR c.nirmata.workflow.details.Scheduler - Could not find run for RunId: Id{id='a14f3b93-bc5e-4b63-9b90-410d331229b6'}
15:35:57.051 [LeaderSelector-1] ERROR c.nirmata.workflow.details.Scheduler - Error while running scheduler
java.lang.RuntimeException: Could not find run for RunId: Id{id='a14f3b93-bc5e-4b63-9b90-410d331229b6'}
        at com.nirmata.workflow.details.Scheduler.updateTasks(Scheduler.java:218) ~[nirmata-workflow-0.6.1-SNAPSHOT.jar:na]
        at com.nirmata.workflow.details.Scheduler.run(Scheduler.java:142) ~[nirmata-workflow-0.6.1-SNAPSHOT.jar:na]
        at com.nirmata.workflow.details.SchedulerSelector.takeLeadership(SchedulerSelector.java:81) [nirmata-workflow-0.6.1-SNAPSHOT.jar:na]
        at com.nirmata.workflow.details.SchedulerSelector.access$000(SchedulerSelector.java:31) [nirmata-workflow-0.6.1-SNAPSHOT.jar:na]
        at com.nirmata.workflow.details.SchedulerSelector$1.takeLeadership(SchedulerSelector.java:52) [nirmata-workflow-0.6.1-SNAPSHOT.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector$WrappedListener.takeLeadership(LeaderSelector.java:536) [curator-recipes-2.6.0.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:398) [curator-recipes-2.6.0.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:443) [curator-recipes-2.6.0.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:63) [curator-recipes-2.6.0.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:244) [curator-recipes-2.6.0.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:238) [curator-recipes-2.6.0.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40-internal]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40-internal]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40-internal]
15:35:57.051 [LeaderSelector-1] INFO  c.n.w.details.SchedulerSelector - 10.10.66.50 is no longer the scheduler
15:35:57.051 [pool-36-thread-56] DEBUG HostGroupController - host lock /Orchestrator/HostGroup/1e55787a-e59a-444d-8787-c93b99cd0b3f acquired
15:35:57.051 [pool-36-thread-56] DEBUG c.n.client.service.DefaultCache - CACHE - get config{type=HostGroup, id=1e55787a-e59a-444d-8787-c93b99cd0b3f} - size=2975 hit=4044506 miss=177934
15:35:57.051 [pool-36-thread-56] DEBUG c.n.client.service.DefaultCache - CACHE - get config{type=Host, id=f6a4a486-2356-4b4e-8b40-897c79b48bf7} - size=2975 hit=4044507 miss=177934
15:35:57.051 [pool-36-thread-56] DEBUG c.n.client.service.DefaultCache - CACHE - get config{type=Host, id=9b6bb115-0333-493

To recover from this situation, I stop the 3 instances, remove the workflow nodes in zookeeper and then restart the 3 instances.

**Comment by Randgalt** [comment]
Are you using an AutoCleaner? If so, is it the StandardAutoCleaner? If so, what value are you using for minAge?

**Comment by dtoledo67** [comment]
Yes, I use the auto cleaner. Here how it is initialized:

        Duration now = Duration.ZERO;
        Duration runPeriod = Duration.ofSeconds(60);
        AutoCleaner cleaner = new StandardAutoCleaner(now);
        WorkflowManagerBuilder workflowManagerBuilder = WorkflowManagerBuilder.builder().withCurator(
            _curator, _groupId, WORKFLOW_VERSION).withAutoCleaner(cleaner, runPeriod);

**Comment by Randgalt** [comment]
OK- that's the problem. If you made the duration a few minutes it wouldn't happen. But, I should ignore the error anyway. I'll work on a fix.

**Comment by dtoledo67** [comment]
Thanks, I'll try that.
