### ISSUE TITLE
Potential thread leak

### ISSUE THREAD

**Issue by dtoledo67** [NirmataOSS/workflow#24]
i noticed that one of my process is leaking threads. It could be due to not always closing the WorkflowManager. Any other possibility?. Here is an example of thread dump:

"SimpleQueue-0" #27573 daemon prio=5 os_prio=0 tid=0x00007f1068a92800 nid=0x6bc8 waiting on condition [0x00007f0f61d5c000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000ca6ff380> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at com.nirmata.workflow.queue.zookeeper.SimpleQueue.runLoop(SimpleQueue.java:197)
        at com.nirmata.workflow.queue.zookeeper.SimpleQueue$$Lambda$17/1746711015.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - <0x00000000bb5b1ab8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by Randgalt** [comment]
I did some tests and I don't see any leaks. Are you certain it's not you?

**Comment by dtoledo67** [comment]
Yes it could be me. I  am trying to isolate the problem. The question I was
asking was about this specific thread. Is there one associated to each
WorkflowManager? Understanding how this tread is created could help me to
isolate the problem.

**Comment by Randgalt** [comment]
There's one for each scheduler of each TaskType. Then there's one for each task executor.

**Comment by Randgalt** [comment]
Is this still an issue?

**Comment by dtoledo67** [comment]
I think I found an issue on my side: some of the workflow managers are
allocated dynamically and never released. You can close this issue.
